### ISSUE TITLE
Untrained Model in the last commit.

### ISSUE THREAD

**Issue by cosmic-heart** [jiseongHAN/Super-Mario-RL#4]
It seems, q_target.pth model is overridden by my model which you merged with the pull request. Actually i just tried for 5 episodes. Get back 39th commit model (your model).

And the q_target.pth in 39th commit having EOF file error. This Model size is 2MB (approx) but it should be 41 MB (approx). So there is mismatch is the state_dict() size.

**Comment by jiseongHAN** [comment]
Hello! Unfortunately, my previous model was already broken, so i have to fit my model again and upload it.

Soon or later I will upload new pre-trained checkpoint.

Thanks a lot!
