### ISSUE TITLE
Inquiry About Training Approach for Super Mario Agent

### ISSUE THREAD

**Issue by asyua-ye** [jiseongHAN/Super-Mario-RL#5]
Hi,

I recently came across your fascinating project on GitHub where you've developed an agent to play Super Mario using reinforcement learning. Your work is truly impressive, and I'm very interested in understanding more about your training methodology.

I was wondering if you could share some insights regarding how you trained your agent:

Did you train the agent on individual levels separately, or was it trained across the entire game directly?
Is the trained model capable of completing the entire Super Mario game without modifications, or does it require level-specific adjustments?
Your answers would greatly help in enhancing my understanding of applying reinforcement learning in complex environments like Super Mario. Thank you very much for your time and for sharing your work with the community.

Best regards,
asyuaye

**Comment by jiseongHAN** [comment]
Hello! I'm very glad for you to visit my repository.

```Did you train the agent on individual levels separately, or was it trained across the entire game directly?```
->  I trained the agent on invidual levels seperately.

```Is the trained model capable of completing the entire Super Mario game without modifications, or does it require level-specific adjustments?```

-> It is possible to complete level without any modifications or level specific features. I only used images to train the agent.

**Comment by asyua-ye** [comment]
Thank you so much for responding to my questions. Your approach to training the agent on individual levels separately is quite intriguing. Just to clarify, does this mean that for completing levels from 1-1 to 8-4, you would need 32 separate models? Or is it possible to continuously switch levels during training on a single model? The latter seems quite challenging to achieve...

Again, thank you for sharing your insights and work. It's greatly appreciated!

**Comment by jiseongHAN** [comment]
My approach was to complete each level with each agent.

It means if you want to make the agent that complete level 1-1 to 8-4, you may need 32 seperate agent.

I wish it is possible to complete whole level with single agent, but I can't ensure the single agent can complete whole level uinsg this repository as is.
(even if the agent is to trained with multiple or random levels.
Maybe you need to fix network architecture or add some preprocessing pipeline to train the agent...)
